<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fs_media_gallery"
 *
 * Auto generated by Extension Builder 2013-02-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Media Gallery',
	'description' => 'A media gallery based on the FAL integration of TYPO3.
Show your media assets from your local or remote storage as a gallery of albums.',
	'category' => 'plugin',
	'author' => 'Frans Saris',
	'author_email' => 'franssaris@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '1.0.0-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.2 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>