<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fs_media_gallery"
 *
 * Auto generated by Extension Builder 2013-02-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Media Gallery',
	'description' => 'A media gallery based on the media/fal extention of TYPO3.
Show your images from your local or remote storage as a gallery of albums.',
	'category' => 'plugin',
	'author' => 'Frans Saris',
	'author_email' => 'franssaris@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>